Privacy Policy
makeopensource/Authenticator pull request #49
Opened 2022-05-09 22:42 UTC by alans-42

2022-05-09 23:13 UTC, alans-42 commented
Generator used: https://app-privacy-policy-generator.nisrulz.com

2022-06-30 02:41 UTC, emilkovacev requested changes
Admittedly it took me some time before I managed to get to this review, but here it is! Just one small change that seems to be preventing the app from running. Once that's done we can look at the functionality and make that pr!

2022-06-30 02:41 UTC, emilkovacev commented on authenticator/App.js
> +import Privacy from './views/privacy-policy';
I believe there is no such file at the moment. We can probably just paste the html that we had from that generator and format it with similar js as before!

2022-07-08 01:57 UTC, alans-42 commented
Sorry I just noticed the comment, but I realized the file with the policy itself was never committed and pushed so I just added it to the pull request.

2022-07-10 00:19 UTC, emilkovacev commented
Thanks for updating the PR! There seem to still be some small bugs I'd like to iron out, but honestly it may be on my end. I'll keep this chat up to date on the progress for the PR, but it should be merged soon :)

2022-09-08 15:49 UTC, closed without merging